#!/bin/bash
sudo sleep 30
sudo apt-get update -y
sudo apt-get install python-dev python-pip -y
sudo pip install --upgrade pip
sudo pip install --upgrade ansible
sudo pip install --upgrade awscli
sudo timedatectl set-timezone Asia/Dhaka
sudo localectl set-locale LANG=en_US.utf8

sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
sudo apt-add-repository 'deb https://apt.dockerproject.org/repo ubuntu-xenial main' -y
sudo apt-get update -y
sudo apt-get install -y docker-engine
sudo systemctl enable docker
sudo usermod -aG docker ubuntu
sudo curl -o /usr/local/bin/docker-compose -L "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)"
sudo chmod u+x /usr/local/bin/docker-compose
